// Code generated by protoc-gen-go-rpc. DO NOT EDIT.

package calc

import (
	"context"
	"mini-rpc/internal/client"
	"mini-rpc/internal/server"
	"google.golang.org/protobuf/proto"
)

type CalculatorClient struct {
	pool *client.Pool
}

func NewCalculatorClient(addr string) *CalculatorClient {
	return &CalculatorClient{pool: client.NewPool(1, addr)}
}

func (c *CalculatorClient) Add(ctx context.Context, req *CalcReq) (*CalcRsp, error) {
	body, err := proto.Marshal(req)
	if err != nil {
		return nil, err
	}
	future, err := c.pool.CallAsync(ctx, "Calculator.Add", client.RoundRobin, body)
	if err != nil {
		return nil, err
	}
	ret, err := future.Get(ctx)
	if err != nil {
		return nil, err
	}
	rsp := &CalcRsp{}
	err = proto.Unmarshal(ret, rsp)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

type CalculatorServer interface {
	Add(context.Context, *CalcReq) (*CalcRsp, error)
}

type CalculatorServerWrapper struct {
	Srv CalculatorServer
}

func (w *CalculatorServerWrapper) Add(body []byte) ([]byte, error) {
	var req CalcReq
	err := proto.Unmarshal(body, &req)
	if err != nil {
		return nil, err
	}
	rsp, err := w.Srv.Add(context.Background(), &req)
	if err != nil {
		return nil, err
	}
	return proto.Marshal(rsp)
}

func RegisterCalculatorServer(s *server.RPCServer, srv CalculatorServer) {
	wrapper := &CalculatorServerWrapper{Srv: srv}
	s.RegisterService("Calculator", wrapper)
}
