// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/codec/proto/calc/calc.proto

package calc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalcReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcReq) Reset() {
	*x = CalcReq{}
	mi := &file_internal_codec_proto_calc_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcReq) ProtoMessage() {}

func (x *CalcReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_proto_calc_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcReq.ProtoReflect.Descriptor instead.
func (*CalcReq) Descriptor() ([]byte, []int) {
	return file_internal_codec_proto_calc_calc_proto_rawDescGZIP(), []int{0}
}

func (x *CalcReq) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *CalcReq) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type CalcRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcRsp) Reset() {
	*x = CalcRsp{}
	mi := &file_internal_codec_proto_calc_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRsp) ProtoMessage() {}

func (x *CalcRsp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_proto_calc_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRsp.ProtoReflect.Descriptor instead.
func (*CalcRsp) Descriptor() ([]byte, []int) {
	return file_internal_codec_proto_calc_calc_proto_rawDescGZIP(), []int{1}
}

func (x *CalcRsp) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_internal_codec_proto_calc_calc_proto protoreflect.FileDescriptor

const file_internal_codec_proto_calc_calc_proto_rawDesc = "" +
	"\n" +
	"$internal/codec/proto/calc/calc.proto\x12\x04calc\"%\n" +
	"\aCalcReq\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\"!\n" +
	"\aCalcRsp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result21\n" +
	"\n" +
	"Calculator\x12#\n" +
	"\x03Add\x12\r.calc.CalcReq\x1a\r.calc.CalcRspB$Z\"mini-rpc/internal/codec/proto/calcb\x06proto3"

var (
	file_internal_codec_proto_calc_calc_proto_rawDescOnce sync.Once
	file_internal_codec_proto_calc_calc_proto_rawDescData []byte
)

func file_internal_codec_proto_calc_calc_proto_rawDescGZIP() []byte {
	file_internal_codec_proto_calc_calc_proto_rawDescOnce.Do(func() {
		file_internal_codec_proto_calc_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_codec_proto_calc_calc_proto_rawDesc), len(file_internal_codec_proto_calc_calc_proto_rawDesc)))
	})
	return file_internal_codec_proto_calc_calc_proto_rawDescData
}

var file_internal_codec_proto_calc_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_codec_proto_calc_calc_proto_goTypes = []any{
	(*CalcReq)(nil), // 0: calc.CalcReq
	(*CalcRsp)(nil), // 1: calc.CalcRsp
}
var file_internal_codec_proto_calc_calc_proto_depIdxs = []int32{
	0, // 0: calc.Calculator.Add:input_type -> calc.CalcReq
	1, // 1: calc.Calculator.Add:output_type -> calc.CalcRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_codec_proto_calc_calc_proto_init() }
func file_internal_codec_proto_calc_calc_proto_init() {
	if File_internal_codec_proto_calc_calc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_codec_proto_calc_calc_proto_rawDesc), len(file_internal_codec_proto_calc_calc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_codec_proto_calc_calc_proto_goTypes,
		DependencyIndexes: file_internal_codec_proto_calc_calc_proto_depIdxs,
		MessageInfos:      file_internal_codec_proto_calc_calc_proto_msgTypes,
	}.Build()
	File_internal_codec_proto_calc_calc_proto = out.File
	file_internal_codec_proto_calc_calc_proto_goTypes = nil
	file_internal_codec_proto_calc_calc_proto_depIdxs = nil
}
