package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			for _, svc := range f.Services {
				generateFile(gen, f, svc)
			}
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, f *protogen.File, svc *protogen.Service) {
	filename := f.GeneratedFilenamePrefix + "_rpc.pb.go"
	g := gen.NewGeneratedFile(filename, f.GoImportPath)

	g.P("// Code generated by protoc-gen-go-rpc. DO NOT EDIT.")
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()

	generateImports(g)
	generateClient(g, svc)
	g.P()
	generateServerInterface(g, svc)
	g.P()
	generateServerWrapper(g, svc)
	g.P()
	generateRegister(g, svc)
}

func generateImports(g *protogen.GeneratedFile) {
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"mini-rpc/internal/client"`)
	g.P(`	"mini-rpc/internal/server"`)
	g.P(`	"google.golang.org/protobuf/proto"`)
	g.P(")")
}

func generateClient(g *protogen.GeneratedFile, svc *protogen.Service) {
	clientName := svc.GoName + "Client"
	serviceName := string(svc.Desc.Name())
	g.P("type ", clientName, " struct {")
	g.P("	pool *client.Pool")
	g.P("}")
	g.P()
	g.P("func New", clientName, "(addr string) *", clientName, " {")
	g.P("	return &", clientName, "{pool: client.NewPool(1, addr)}")
	g.P("}")
	g.P()

	for _, method := range svc.Methods {
		inputType := method.Input.GoIdent
		outputType := method.Output.GoIdent
		methodName := string(method.Desc.Name())
		fullName := serviceName + "." + methodName

		g.P("func (c *", clientName, ") ", method.GoName, "(ctx context.Context, req *", inputType, ") (*", outputType, ", error) {")
		g.P("	body, err := proto.Marshal(req)")
		g.P("	if err != nil {")
		g.P("		return nil, err")
		g.P("	}")
		g.P(`	future := c.pool.CallAsync(ctx, "`, fullName, `", client.RoundRobin, body)`)
		g.P("	ret, err := future.Get()")
		g.P("	if err != nil {")
		g.P("		return nil, err")
		g.P("	}")
		g.P("	rsp := &", outputType, "{}")
		g.P("	err = proto.Unmarshal(ret, rsp)")
		g.P("	if err != nil {")
		g.P("		return nil, err")
		g.P("	}")
		g.P("	return rsp, nil")
		g.P("}")
		g.P()
	}
}

func generateServerInterface(g *protogen.GeneratedFile, svc *protogen.Service) {
	serverName := svc.GoName + "Server"
	g.P("type ", serverName, " interface {")
	for _, method := range svc.Methods {
		inputType := method.Input.GoIdent
		outputType := method.Output.GoIdent
		g.P(method.GoName, "(context.Context, *", inputType, ") (*", outputType, ", error)")
	}
	g.P("}")
}

func generateServerWrapper(g *protogen.GeneratedFile, svc *protogen.Service) {
	wrapperName := svc.GoName + "ServerWrapper"
	serverName := svc.GoName + "Server"
	g.P("type ", wrapperName, " struct {")
	g.P("	Srv ", serverName)
	g.P("}")
	g.P()

	for _, method := range svc.Methods {
		inputType := method.Input.GoIdent
		// outputType := method.Output.GoIdent

		g.P("func (w *", wrapperName, ") ", method.GoName, "(body []byte) ([]byte, error) {")
		g.P("	var req ", inputType)
		g.P("	err := proto.Unmarshal(body, &req)")
		g.P("	if err != nil {")
		g.P("		return nil, err")
		g.P("	}")
		g.P("	rsp, err := w.Srv.", method.GoName, "(context.Background(), &req)")
		g.P("	if err != nil {")
		g.P("		return nil, err")
		g.P("	}")
		g.P("	return proto.Marshal(rsp)")
		g.P("}")
		g.P()
	}
}

func generateRegister(g *protogen.GeneratedFile, svc *protogen.Service) {
	serverName := svc.GoName + "Server"
	wrapperName := svc.GoName + "ServerWrapper"
	serviceName := string(svc.Desc.Name())
	g.P("func Register", serverName, "(s *server.RPCServer, srv ", serverName, ") {")
	g.P("	wrapper := &", wrapperName, "{Srv: srv}")
	g.P(`	s.RegisterService("`, serviceName, `", wrapper)`)
	g.P("}")
}
